import os
import ast
import json
import sys
import importlib.metadata
from collections import defaultdict

def get_stdlib_names():
    """获取Python标准库列表，用于过滤（如 os, sys, re 不会被写入 requirements）"""
    if sys.version_info >= (3, 10):
        return sys.stdlib_module_names
    else:
        # 兼容旧版本，这是一个基础列表
        return {
            'os', 'sys', 're', 'math', 'json', 'time', 'datetime', 'random', 
            'collections', 'itertools', 'functools', 'pathlib', 'shutil', 
            'subprocess', 'typing', 'copy', 'io', 'csv', 'warnings'
        }

def get_imports_from_file(file_path):
    """读取文件并解析AST，提取导入的模块名"""
    imports = set()
    
    try:
        if file_path.endswith('.ipynb'):
            # 处理 Jupyter Notebook
            with open(file_path, 'r', encoding='utf-8') as f:
                notebook = json.load(f)
                # 只提取代码单元格
                code_lines = []
                for cell in notebook.get('cells', []):
                    if cell['cell_type'] == 'code':
                        code_lines.extend(cell.get('source', []))
                content = "".join(code_lines)
        else:
            # 处理 Python 脚本
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()
        
        # 解析抽象语法树 (AST)
        tree = ast.parse(content)
        
        for node in ast.walk(tree):
            # 处理 import xxx
            if isinstance(node, ast.Import):
                for alias in node.names:
                    imports.add(alias.name.split('.')[0])
            # 处理 from xxx import yyy
            elif isinstance(node, ast.ImportFrom):
                if node.module:
                    imports.add(node.module.split('.')[0])
                    
    except Exception as e:
        print(f"⚠️ 解析警告: 无法读取 {file_path} - {e}")
        
    return imports

def map_import_to_package():
    """建立 导入名 -> 安装包名 的映射 (例如 cv2 -> opencv-python)"""
    mapping = defaultdict(list)
    try:
        # 获取当前环境所有已安装的包分布
        packages = importlib.metadata.packages_distributions()
        for import_name, package_names in packages.items():
            for pkg in package_names:
                mapping[import_name].append(pkg)
    except AttributeError:
        print("❌ 您的 Python 版本过低，建议升级到 3.10+ 以获得最佳探测效果。")
    return mapping

def generate_robust_requirements():
    print("🔍 开始深度扫描当前目录下的 .py 和 .ipynb 文件...")
    
    # 1. 准备工作
    target_files = []
    for root, dirs, files in os.walk('.'):
        # 排除虚拟环境目录 (常见命名)
        if any(v in root for v in ['venv', '.git', '__pycache__', '.ipynb_checkpoints']):
            continue
        for file in files:
            if file.endswith(('.py', '.ipynb')):
                target_files.append(os.path.join(root, file))
    
    print(f"📄 找到 {len(target_files)} 个代码文件。")
    
    # 2. 提取所有导入
    all_imports = set()
    stdlib = get_stdlib_names()
    
    for file in target_files:
        file_imports = get_imports_from_file(file)
        # 过滤标准库 (如 os, sys) 和 相对导入
        clean_imports = {i for i in file_imports if i not in stdlib and not i.startswith('_')}
        all_imports.update(clean_imports)
        
    print(f"🧩 提取到 {len(all_imports)} 个第三方库引用: {all_imports}")

    # 3. 映射到真实安装版本 (核心步骤)
    import_to_pkg = map_import_to_package()
    final_requirements = {}
    missing_packages = []
    
    for module in all_imports:
        # 尝试查找对应的安装包
        package_names = import_to_pkg.get(module)
        
        if package_names:
            # 通常取第一个匹配的包名
            pkg_name = package_names[0]
            try:
                version = importlib.metadata.version(pkg_name)
                final_requirements[pkg_name] = version
            except importlib.metadata.PackageNotFoundError:
                missing_packages.append(module)
        else:
            # 有些包 import 名字就是包名，但无法通过 distribution 找到（少数情况）
            # 或者该包尚未安装
            missing_packages.append(module)

    # 4. 写入文件
    output_file = "requirements.txt"
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("# Generated by Auto-Detector\n")
        for pkg, ver in sorted(final_requirements.items()):
            f.write(f"{pkg}=={ver}\n")
            
    # 5. 结果汇报
    print("\n" + "="*40)
    print(f"✅ 成功生成: {output_file}")
    print("="*40)
    print("📦 包含库:")
    for pkg, ver in final_requirements.items():
        print(f" - {pkg} == {ver}")
        
    if missing_packages:
        print("\n⚠️ 警告: 代码中引用了以下库，但当前环境未检测到安装 (或映射失败):")
        print(f"   {missing_packages}")
        print("   (原因可能是: 你没有安装它，或者它是本地文件 import)")

# 运行主程序
generate_robust_requirements()